adapt to new local function and resources names
Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>

diff --git a/systemtests/tests/ndmp-bareos/testrunner-omnios b/systemtests/tests/ndmp-bareos/testrunner-omnios
--- a/systemtests/tests/ndmp-bareos/testrunner-omnios
+++ b/systemtests/tests/ndmp-bareos/testrunner-omnios
@@ -1,4 +1,22 @@
 #!/bin/bash
+#   BAREOS® - Backup Archiving REcovery Open Sourced
+#
+#   Copyright (C) 2025 Bareos GmbH & Co. KG
+#
+#   This program is Free Software; you can redistribute it and/or
+#   modify it under the terms of version three of the GNU Affero General Public
+#   License as published by the Free Software Foundation and included
+#   in the file LICENSE.
+#
+#   This program is distributed in the hope that it will be useful, but
+#   WITHOUT ANY WARRANTY; without even the implied warranty of
+#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
+#   Affero General Public License for more details.
+#
+#   You should have received a copy of the GNU Affero General Public License
+#   along with this program; if not, write to the Free Software
+#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+#   02110-1301, USA.
 
 set -e
 set -o pipefail
@@ -6,9 +24,9 @@ set -u
 
 #
 # Requirements:
-# * This tests is implemented for a Isilon NDMP storage.
+# * This tests is implemented for a OmniOS NDMP storage.
 # * To create and delete backup data,
-#   password-less SSH root access to the Isilon storage is required.
+#   password-less SSH root access to the Omnios storage is required.
 # * run cmake with parameter matching your environment:
 #     -Dndmp_data_agent_address=<ip.of.data.agent> \
 #     -Dndmp_data_agent_user=<user> \
@@ -30,93 +48,76 @@ fi
 "${rscripts}"/cleanup
 "${rscripts}"/setup
 
-os_type=$(uname -s)
-if [ "$os_type" = "Darwin" ] || [ "$os_type" = "FreeBSD" ]; then
-  SED="sed -i ''"
-else
-  SED="sed --in-place"
-  if [ "$os_type" = "Windows" ]; then
-    conf=$(cygpath -w "${BAREOS_CONFIG_DIR}")
-  fi
-fi
-
-
-wait_jobid()
-{
-  JOBID=$1
-  TIMEOUT=${2:-5}
-
-  while [ $TIMEOUT -gt 0 ] && ${BCONSOLE} <<< "wait jobid=${JOBID}" | grep "JobStatus=Unknown"; do
-    sleep 1
-    TIMEOUT=$((TIMEOUT-1))
-  done
-  ${BCONSOLE} <<< "wait jobid=${JOBID}"
-}
-
-check_jobid()
-{
-  JOBID=$1
-
-  wait_jobid ${JOBID}
-  #echo "messages" | ${BCONSOLE}
-  RESULT=$(${BCONSOLE} <<< "list joblog jobid=${JOBID}")
-  if grep 'Fatal error:' <<< "${RESULT}"; then
-    set_error "${RESULT}"
-    exit 1
-  fi
-  if ! grep 'Termination:.*OK' <<< "${RESULT}"; then
-    set_error "${RESULT}"
-    exit 1
-  fi
-}
-
-cleanup_isilon()
-{
-  ${SSH} rm -Rf /${mountpoint}/home/regress/${NDMP_FILESYSTEM}
-  ${SSH} rm -Rf /${mountpoint}/home/regress/bareos-restores-${NDMP_FILESYSTEM}
-  ${SSH} rm -Rf /${mountpoint}/data/bareos-restores-${NDMP_FILESYSTEM}
-}
-
 start_test
 
 start_bareos
 
 BCONSOLE=bin/bconsole
 STARTJOBID=1
-NDMPCLIENT=isilon
-SSH="ssh root@${NDMP_DATA_AGENT_ADDRESS} -o StrictHostKeyChecking=no"
-NDMP_FILESYSTEM=$IP_ADDRESS_TO_ACCESS_NDMP_DATA_AGENT
+NDMPCLIENT=omnios
 
-echo "status client=$NDMPCLIENT" | ${BCONSOLE}
-echo "status director" | ${BCONSOLE}
+${BCONSOLE} <<< "status client=ndmp-fd
+status director
+status storage=ndmpfile
+"
 
-cleanup_isilon
-${SSH} mkdir -p /${mountpoint}/home/regress/${NDMP_FILESYSTEM}
-${SSH} dd if=/dev/zero of=/${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full bs=1M count=20
-${SSH} "echo ${NDMP_FILESYSTEM} >> /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full"
-${SSH} "cat - > /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/testfile" < sbin/bareos_dir-ndmp-bareos
-# we need an additional file, so the restore doesn't pick the last file of the volume and
-# data stream
-${SSH} "cat - > /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/testfile2" < sbin/bareos_sd-ndmp-bareos
+cleanup_remote
 
-echo "################ running NDMP failing backup full #####################"
+echo "################ running NDMP failing first full to trigger rerun #####################"
 
-echo "run job=${NDMPCLIENT}dump level=Full yes" | ${BCONSOLE}
-check_jobid $((STARTJOBID))
+${BCONSOLE} <<< "run job=NDMPBackupDump fileset=${NDMPCLIENT}-fileset level=Full yes"
+check_jobid_failed $((STARTJOBID))
 
+# Create data so rescheduled job will work
+make_data_remote
+sleep 60
 
-echo "################ rerun of NDMP backup full #####################"
-check_jobid $((STARTJOBID+1))
+# Once fixed use check_jobid instead
+# ``Fatal error: No backup type specified in NDMP job``
+check_jobid_failed $((STARTJOBID))
 
+# To be fixed storage should not wait anymore the FD connection.
+# With client passive = yes, this is working immediately.
+# but not always ...
+#status storage=ndmpfile
+#Job inventory:
+#
+#Backup Job omniosdump.2025-08-18_14.06.34_05 waiting for Client connection.
+#JobId=1 Level=Full Type=Backup Name=omniosdump Status=Waiting on FD
+#Writing: Volume="isilon-0001"
+#    pool="isilon" device="FileStorage" (storage)
+#    spooling=0 despooling=0 despool_wait=0
+#    Files=0 Bytes=0 AveBytes/sec=0 LastBytes/sec=0
+#    FDSocket closed
+#
+#====
+#
+#Jobs waiting to reserve a drive:
+#====
+#
+#Terminated Jobs:
+# JobId  Level    Files      Bytes   Status   Finished        Name
+#===================================================================
+#     1  Full          1       112   Cancel   18-Aug-25 14:06 omniosdump
+#
+
+status_storage=$(${BCONSOLE} <<< "status storage=ndmpfile")
+if grep 'Status=Waiting on FD' <<< "${status_storage}"; then
+  set_error "${RESULT}"
+  exit 1
+fi
+
+# At that point the storage has release the resource
+echo "################ rerun manually NDMP backup full #####################"
 
 ### Fix the failing job
-${SED} "/Fileset.*=.*/d" "{conf}/etc/bareos/bareos-dir.d/job/isilondump"
-${BCONSOLE} <<< "reload"
-
-echo "rerun jobid=${STARTJOBID} yes" | ${BCONSOLE}
+$BCONSOLE <<< "rerun jobid=${STARTJOBID} yes"
 STARTJOBID=$((STARTJOBID+1))
 check_jobid $((STARTJOBID))
 
+# Jobid 2 might failed if restarted while the Storage is still waiting on previous FD
+# If all jobs are canceled we might have this issue at the end of jobid 2
+# bareos-dir JobId 2: Fatal error: NumConcurrentJobs Dec Wstore=LocalfileStorage wncj=-1
 
 
 echo "################ running NDMP backup incrementals #####################"
@@ -124,103 +125,116 @@ ${SSH} dd if=/dev/zero of=/${mountpoint}/home/regress/${NDMP_FILESYSTEM}/increme
 
 for ID in $(seq 1 10); do
   ${SSH} "echo ${NDMP_FILESYSTEM}-${ID} >> /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/incremental"
-  echo "run job=${NDMPCLIENT}dump level=Incremental yes" | ${BCONSOLE}
+  ${BCONSOLE} <<< "run job=NDMPBackupDump fileset=${NDMPCLIENT}-fileset level=Incremental yes"
   check_jobid $((STARTJOBID+${ID}))
 done
 
 # restore
 
 # remove files
-cleanup_isilon
+cleanup_remote
 
 echo "################ restore single file #####################"
 # restore  single file
-${BCONSOLE} << EOMSG
-restore jobid=$((STARTJOBID)) client=isilon fileset=isilon-fileset restorejob=NDMPRestoreDump select yes
+${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump select yes
 mark /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/testfile
 done
 wait
-EOMSG
-
+"
 ((ID++))
 check_jobid $((STARTJOBID+${ID}))
 
-${SSH} "cat /ifs/home/regress/${NDMP_FILESYSTEM}/testfile" | diff - sbin/bareos_dir-ndmp-bareos
+${SSH} "cat /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/testfile" | diff - sbin/bareos_dir-ndmp-bareos
 
 # remove files
-${SSH} rm -Rf /ifs/home/regress/${NDMP_FILESYSTEM}
+cleanup_remote
 
 
 echo "################ restore full #####################"
 # restore full
-echo "restore jobid=$((STARTJOBID)) client=isilon fileset=isilon-fileset restorejob=NDMPRestoreDump all done yes"  | ${BCONSOLE}
+${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump all done yes"
 ((ID++))
 check_jobid $((STARTJOBID+${ID}))
 
-${SSH} "tail -c 200 /ifs/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
+${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
 
+# remove files
+cleanup_remote
 
 echo "################ restore full to different RELATIVE location /prefix #####################"
 # restore full to different RELATIVE location "/prefix"
-echo "restore jobid=$((STARTJOBID)) client=isilon fileset=isilon-fileset restorejob=NDMPRestoreDump  where=/bareos-restores-${NDMP_FILESYSTEM} all done yes"  | ${BCONSOLE}
+${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump where=/bareos-restores-${NDMP_FILESYSTEM} all done yes"
 ((ID++))
 check_jobid $((STARTJOBID+${ID}))
 
-${SSH} "tail -c 200 /ifs/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
-#${SSH} "grep ${NDMP_FILESYSTEM} /ifs/home/regress/${NDMP_FILESYSTEM}/bareos-restores-${NDMP_FILESYSTEM}/full"
+# Shouldn't that failed ?
+${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
+# and this one working ?
+#${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/bareos-restores-${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
+
+# remove files
+cleanup_remote
 
 echo "################ restore full to different ABSOLUTE location ^/prefix #####################"
 # restore full to different ABSOLUTE location "^/prefix"
-
-echo "restore jobid=$((STARTJOBID)) client=isilon fileset=isilon-fileset restorejob=NDMPRestoreDump  where=^/ifs/data/bareos-restores-${NDMP_FILESYSTEM} all done yes"  | ${BCONSOLE}
+${BCONSOLE} <<< "restore jobid=$((STARTJOBID)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump where=^/${mountpoint}/data/bareos-restores-${NDMP_FILESYSTEM} all done yes"
 ((ID++))
 check_jobid $((STARTJOBID+${ID}))
 
-${SSH} "tail -c 200 /ifs/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
-#${SSH} "grep ${NDMP_FILESYSTEM} /ifs/data/bareos-restores-${NDMP_FILESYSTEM}/full"
+${SSH} "tail -c 200 /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
+
+#${SSH} "tail -c 200 /${mountpoint}/data/bareos-restores-${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
+
+# remove files
+cleanup_remote
 
 echo "################ restore incremental #####################"
 # restore incremental
-printf "restore jobid=$((STARTJOBID+1)) client=isilon fileset=isilon-fileset restorejob=NDMPRestoreDump select current\rmark /ifs/home/regress/${NDMP_FILESYSTEM}/incremental\rdone\ryes\r" | ${BCONSOLE}
+${BCONSOLE} <<< "restore jobid=$((STARTJOBID+1)) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump select current
+mark /${mountpoint}/home/regress/${NDMP_FILESYSTEM}/incremental
+done
+yes
+"
 ((ID++))
 check_jobid $((STARTJOBID+${ID}))
 
-${SSH} "tail -c 200 /ifs/home/regress/${NDMP_FILESYSTEM}/incremental | grep ${NDMP_FILESYSTEM}"
-#${SSH} "grep ${NDMP_FILESYSTEM} /ifs/home/regress/${NDMP_FILESYSTEM}/incremental"
+${SSH} "tail -c 200 /${mount_point}/home/regress/${NDMP_FILESYSTEM}/incremental | grep ${NDMP_FILESYSTEM}-1"
 
 # cleanup
-cleanup_isilon
+cleanup_remote
+
+exit 0
 
 echo "################ run copy job #####################"
 # run copy job
-echo "run job=ndmp-copy-$NDMPCLIENT yes"  | ${BCONSOLE}
-echo "wait"  | ${BCONSOLE}
-echo "messages"  | ${BCONSOLE}
-
+${BCONSOLE} <<< "run job=ndmp-copy-$NDMPCLIENT yes
+wait
+messages
+"
 echo "################ restore copy of full job #####################"
 
 # restore copy
 ID=18
-echo "restore jobid=$((STARTJOBID+${ID})) client=isilon fileset=isilon-fileset restorejob=NDMPRestoreDump all done yes"  | ${BCONSOLE}
-echo "wait"  | ${BCONSOLE}
-echo "messages"  | ${BCONSOLE}
-${SSH} "tail -c 200 /ifs/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
-#${SSH} "grep ${NDMP_FILESYSTEM} /ifs/home/regress/${NDMP_FILESYSTEM}/full"
+${BCONSOLE} <<< restore jobid=$((STARTJOBID+${ID})) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump all done yes
+wait
+messages
+${SSH} "tail -c 200 /${mount_point}/home/regress/${NDMP_FILESYSTEM}/full | grep ${NDMP_FILESYSTEM}"
+#${SSH} "grep ${NDMP_FILESYSTEM} /${mount_point}/home/regress/${NDMP_FILESYSTEM}/full"
 
-cleanup_isilon
+cleanup_remote
 
 ID=28
 echo "################ restore copy of incremental job #####################"
 # restore copy of incremental
-echo "restore jobid=$((STARTJOBID+${ID})) client=isilon fileset=isilon-fileset restorejob=NDMPRestoreDump all done yes"  | ${BCONSOLE}
-echo "wait"  | ${BCONSOLE}
-echo "messages"  | ${BCONSOLE}
-#${SSH} "grep ${NDMP_FILESYSTEM} /ifs/home/regress/${NDMP_FILESYSTEM}/incremental"
-${SSH} "tail -c 200 /ifs/home/regress/${NDMP_FILESYSTEM}/incremental | grep ${NDMP_FILESYSTEM}"
+${BCONSOLE} <<< "restore jobid=$((STARTJOBID+${ID})) client=ndmp-fd fileset=${NDMP_CLIENT}-fileset restorejob=NDMPRestoreDump all done yes
+wait
+messages
+"
+${SSH} "tail -c 200 /${mount_point}/home/regress/${NDMP_FILESYSTEM}/incremental | grep ${NDMP_FILESYSTEM}"
 
 # final cleanup
-cleanup_isilon
+cleanup_remote
 
-check_for_zombie_jobs storage=isilonfile client=bareos-fd
+check_for_zombie_jobs storage=ndmpfile client=ndmp-fd
 
 end_test
