wip: testrunner-default simplify number of tests, incremental can be skipped as equal to full

diff --git a/systemtests/tests/py3plug-fd-contrib-mariadb_dump/testrunner-default b/systemtests/tests/py3plug-fd-contrib-mariadb_dump/testrunner-default
--- a/systemtests/tests/py3plug-fd-contrib-mariadb_dump/testrunner-default
+++ b/systemtests/tests/py3plug-fd-contrib-mariadb_dump/testrunner-default
@@ -14,7 +14,7 @@ export TestName
 
 JobName=backup-bareos-fd
 test_db_name="${db_name}_test"
-RESTORE_DIR="$tmp/bareos-restores/@mariadbbackup@/"
+RESTORE_DIR="${tmp}/bareos-restores/@mariadbbackup@/"
 
 #shellcheck source=../scripts/functions
 . "${rscripts}"/functions
@@ -22,8 +22,6 @@ skip_if_root
 
 #shellcheck source=../scripts/mysql.sh
 . "${rscripts}"/mariadb.sh
-# "${rscripts}"/cleanup
-# "${rscripts}"/setup
 
 mariadb_init
 mariadb_server_start
@@ -38,7 +36,7 @@ cat <<END_OF_DATA >${tmp}/bconcmds
 @$out ${NULL_DEV}
 messages
 @$out ${tmp}/log1.out
-setdebug level=500 trace=1 timestamp=1 client=bareos-fd
+setdebug level=200 trace=1 timestamp=1 client=bareos-fd
 run job=${JobName} yes
 wait
 setdebug level=0 client=bareos-fd
@@ -52,53 +50,23 @@ END_OF_DATA
 
 run_bconsole
 expect_grep "Backup OK" "${tmp}/log1.out" "Full Backup not found!"
+if [ ${estat} -ne 0 ]; then
+    exit ${estat}
+fi
+# No need to test incremental, as dumps are always full
 
-# insert data and run incremental
-echo "insert into test (data) VALUES ('test entry 2') " | ${MARIADB_CLIENT} "${test_db_name}"
-
-cat <<END_OF_DATA2>${tmp}/bconcmds
-@$out ${NULL_DEV}
-messages
+cat <<END_OF_DATA2 >"${tmp}/bconcmds"
 @$out ${tmp}/log2.out
-setdebug level=500 trace=1 timestamp=1 client=bareos-fd
-run job=${JobName} Level=Incremental yes
-wait
-setdebug level=0 client=bareos-fd
-messages
-llist jobs job=$JobName
-END_OF_DATA2
-
-run_bconsole
-expect_grep "Backup OK" "${tmp}/log2.out" "Incremental Backup not found!"
-
-# run incremental again without any new data
-cat <<END_OF_DATA3 >"$tmp/bconcmds"
-@$out ${tmp}/log3.out
-setdebug level=500 trace=1 timestamp=1 client=bareos-fd
-run job=${JobName} yes
-wait
-setdebug level=0 client=bareos-fd
-status dir
-llist jobs job=$JobName
-END_OF_DATA3
-
-run_bconsole
-expect_grep "Backup OK" "${tmp}/log3.out" "Empty Incremental Backup not found!"
-
-
-cat <<END_OF_DATA4 >"${tmp}/bconcmds"
-@$out ${tmp}/log4.out
-setdebug level=500 trace=1 timestamp=1 client=bareos-fd
+setdebug level=200 trace=1 timestamp=1 client=bareos-fd
 restore restorejob=RestoreFile client=bareos-fd fileset=bareos_mariadb_dump yes select all done
 wait
 setdebug level=0 client=bareos-fd
 status dir
 llist jobs job=RestoreFile
-END_OF_DATA4
+END_OF_DATA2
 
 run_bconsole
-expect_grep "Restore OK" "${tmp}/log4.out" "Restore OK not found!"
-
+expect_grep "Restore OK" "${tmp}/log2.out" "Restore OK not found!"
 
 # Check if some files are restored
 ls -lR "${RESTORE_DIR}"
